language: "ko-KR"
early_access: false
tone_instructions: "'~했어요!'나 '~하셨나요?', '~걸까요??', '~할 것 같아요~!', '~해요.', '~요ㅎㅎ' 와 같은 어미를 사용해서 친근하고 다정한 톤으로 리뷰해주세요."

reviews:
  high_level_summary: true
  review_status: true
  path_filters:
    - "!**/.xml"
    - "!**/__generated__/**"
    - "!**/generated/**"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.gif"
    - "!**/*.lock"

  path_instructions:
    - path: "**/*.kt"
      instructions: |
        "전체 코틀린 코드에 대해 다음 기준에 따라 리뷰해주세요!

        📌 코드 품질:
        - 로직 오류나 예외 상황은 없는지요?
        - 성능을 개선할 수 있는 여지가 있을까요?
        - 보안적으로 민감한 로직은 안전하게 작성되었는지 확인해주세요!
        - 확장성 측면에서 향후 기능 추가가 유연하게 가능할지 봐주세요.

        🏗 아키텍처 & 설계:
        - SOLID 원칙을 잘 지키고 있나요? (특히 SRP와 OCP)
        - 디자인 패턴을 사용할 수 있는 영역이 보일까요?
        - 모듈 간 결합도는 낮고 응집도는 높은가요?
        - 외부 라이브러리나 모듈에 과하게 의존하고 있진 않나요?
        - 도메인 주도 설계(DDD) 관점에서 적절한 책임 분리가 이루어졌는지도 확인해주세요.

        🔧 유지보수성:
        - 코드 복잡도는 적절한가요? 너무 많은 책임을 가진 함수는 없나요?
        - 테스트하기 쉬운 구조인가요? (의존성 분리 등)
        - 문서화나 주석이 필요한 부분은 있나요?
        - 기술적 부채로 이어질 수 있는 임시 코드나 하드코딩은 없는지 확인해주세요!

        또한 코틀린 관용구, null 처리, 불변성(val 사용), 확장 함수 활용 등 코틀린답게 작성되었는지도 함께 검토해주세요.
        
        ✅ Service 클래스:
        - @Transactional 사용이 적절한가요?
        - 비즈니스 로직의 책임이 명확한가요?
        - 예외 처리가 일관되게 처리되고 있나요?
        - 의존성 주입이 생성자 기반으로 이뤄지고 있나요?
        
        ✅ Controller 클래스:
        - REST API의 URI, HTTP 메서드 설계가 직관적인가요?
        - 요청 및 응답 포맷이 일관되고 표준적인가요?
        - 예외 발생 시 적절한 에러 응답을 리턴하고 있나요?
        "

    - path: "src/main/kotlin/com/makao/deploy/entity/**/*.kt"
      instructions: |
        "엔티티는 아래 사항을 확인해주세요!
        - @Entity 설정이 적절한가요?
        - 연관관계 매핑이 잘 되어있나요?
        - 불변성을 잘 지키고 있나요?
        - 비즈니스 로직이 최소화되어 있나요?
        - DDD에서 말하는 '도메인 모델은 상태와 행위를 함께 갖는다'는 원칙이 잘 지켜지고 있는지도 봐주세요."

    - path: "src/main/kotlin/com/makao/deploy/repository/**/*.kt"
      instructions: |
        "리포지토리는 아래 사항을 확인해주세요!
        - 쿼리 메소드 네이밍이 명확한가요?
        - N+1 문제는 없나요?
        - 페이징/정렬이 필요한 경우 적절히 구현되어 있나요?
        - Spring Data JPA의 기능을 잘 활용하고 있나요?"

    - path: "src/main/resources/application*.yml"
      instructions: |
        "설정 파일은 아래 사항을 확인해주세요!
        - 프로파일 분리가 잘 되어있나요? (dev, prod 등)
        - 민감 정보가 하드코딩되어 있지 않나요?
        - JPA 및 DB 관련 설정이 명확하게 정의되어 있나요?"

    - path: "src/test/kotlin/com/makao/deploy/**/*.kt"
      instructions: |
        "테스트 코드는 아래 사항을 확인해주세요!
        - given-when-then 패턴을 따르나요?
        - 테스트 격리가 잘 되어있나요? (데이터 클리어 등)
        - 모킹이 필요한 경우 적절히 사용되었나요?
        - 테스트 커버리지나 중요 비즈니스 로직 테스트 여부도 확인해주세요."

  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
    drafts: false
    base_branches:
      - "main"
      - "develop"
      - "feature/*"
      - "bugfix/*"

chat:
  auto_reply: true
