spring:
  application:
    name: makao-deploy
  profiles:
    active: db, kafka, client

server:
  port: ${MAKAO_DEPLOY_SERVER_PORT:8181}

logging:
  level:
    root: INFO
    com.makao.deploy: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO