spring:
  application:
    name: makao-deploy
  profiles:
    active: local-db
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181

logging:
  level:
    root: INFO
    com.makao.deploy: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 