spring:
  datasource:
    url: ${MAKAO_DEPLOY_DB_URL:jdbc:postgresql://makao-deploy-db:5432/makao_deploy_db}
    username: ${MAKAO_DEPLOY_DB_USERNAME:makao}
    password: ${MAKAO_DEPLOY_DB_PASSWORD:test1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${MAKAO_DEPLOY_DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${MAKAO_DEPLOY_DB_FORMAT_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect